### ISSUE TITLE
NullCounter can't work because woIDs quality is bad

### ISSUE THREAD

**Issue by ImTaki** [ImTaki/OPERA#8]
Alec implements some changes to make sure the script can work in 2 PO mode. 

The condition has this statement `IsGood(Me.WoIDs)`. This value is in bad quality if the line run in 1 PO mode. So the if statement will be always false.

We need to put this if statement out of the several  `and` statement.

```Visual Basic
IsGood(Me.seq_no) and IsGood(me.wo_id) and IsGood(Me.WoIDs) and Me.seq_no <> "" and Me.WoIDs <> ""
```

**Comment by ImTaki** [comment]
I separate this statement into another if statement.

```Visual Basic
try
	
	factResult = aaFactMES.aaClientSession.GetInstance();

	if factResult.Success then
		clientSession = factResult.aaClientSession_Value;

		' If no session exists, start one and then re-initialize node to update SQL with new session
		if clientSession.SessionId == -1 then
			factResult = clientSession.StartSession(aaFactMES.aaClientTypes.clientOperator);
		else
			if IsGood(Me.WoIDs) then
			' 2 PO Mode handling - Alec Weaver - 2019/04/11
				if IsGood(Me.seq_no) and IsGood(me.wo_id) and Me.seq_no <> "" and Me.WoIDs <> "" then
				
					LogMessage("Null counter add record : 2 PO Mode");
					result = aaMES.Prod.aaJobExec.AddProd(clientSession.SessionId,"Default Background User", Me.ent_id,0,2,null,null,null,null,null,Me.item_id,null,null,null,null,null,null,null,null,mesString,mesString,mesString,mesString,0,null,returnID,returnProd);
					result = aaMES.Prod.aaJobExec.AddProd(clientSession.SessionId,"Default Background User", Me.ent_id,0,2,null,null,null,null,null,Me.item_id,null,null,null,null,null,null,null,null,mesString,mesString,mesString,mesString,1,null,returnID,returnProd);
				
				endif;
			else
				' 1 PO Mode handling - Alec Weaver - 2019/04/11
				if IsGood(Me.seq_no) and IsGood(me.wo_id) and Me.seq_no <> "" and Me.wo_id <> "" then
					LogMessage("Null counter add record : 1 PO Mode");
					result = aaMES.Prod.aaJobExec.AddProd(clientSession.SessionId,"Default Background User", Me.ent_id,0,2,null,null,null,null,null,Me.item_id,null,null,null,null,null,null,null,null,mesString,mesString,mesString,mesString,null,null,returnID,returnProd);
				
				endif;
			endif;
		endif;
	endif;
catch
	LogError("Unknown error in Script.NullCounter: " + error.Message);
endtry;
```

**Comment by EloEntropy** [comment]
The bad quality is because the lines have not been deployed after making changes to the attribute name for the Tufting and Packaging lines. The attribute for WoIDs was incorrectly named before, and did not match the Injection lines, so I corrected the names and then added bindings to the NullCounter objects. I didn't deploy the lines because they were in production at the time, but I should have waited to deploy the nullcounter object changes as well.

If you want to leave this code in, that's fine. But once the lines are deployed it would be better to have the original logic in place. That way we don't miss any incorrect bindings for future lines and end up only creating records for 1 PO while still trying to run 2 POs.

**Comment by EloEntropy** [comment]
If you follow the input source on the NullCounter WoIDs attribute in object viewer you will find the attribute I am referring to. I think it is best to keep 2 PO and 1 PO as similar as possible, which is why I designed the objects this way. You currently have separate templates and attributes and code in place for 2 PO, which could make development and maintenance harder in the future. By sharing the same attribute name, you don't need to have special conditions for the null counter scripts, you can keep it generic and it will work for both systems.

**Comment by ImTaki** [comment]
I just use attribute the woIDs quality to determine if the line or equipment is run in 1 PO or 2 PO mode.

Logic is still the same as originally designed.

All lines follow the same logic.
